export const homonymsEN: { [index: string]: string[] } = {
    'abel': ['able'],
    'able': ['abel'],
    'accede': ['exceed'],
    'accept': ['except'],
    'acclamation': ['acclimation'],
    'acclimation': ['acclamation'],
    'acts': ['ax'],
    'ad': ['add'],
    'adam': ['atom'],
    'add': ['ad'],
    'addition': ['edition'],
    'adds': ['adz', 'ads'],
    'adherence': ['adherents'],
    'adherents': ['adherence'],
    'adieu': ['ado'],
    'ado': ['adieu'],
    'ads': ['adds', 'adz'],
    'adz': ['ads', 'adds'],
    'aerial': ['ariel'],
    'affect': ['effect'],
    'affected': ['effected'],
    'affects': ['effects'],
    'afterward': ['afterword'],
    'afterword': ['afterward'],
    'aid': ['aide'],
    'aide': ['aid'],
    'ail': ['ale'],
    'air': ['heir', 'err'],
    'aisle': ['isle', 'I\'ll'],
    'ale': ['ail'],
    'all': ['awl'],
    'all ready': ['already'],
    'all together': ['altogether'],
    'all ways': ['always'],
    'allowed': ['aloud'],
    'allude': ['elude'],
    'alluded': ['eluded'],
    'allusion': ['illusion'],
    'allusive': ['elusive', 'illusive'],
    'aloud': ['allowed'],
    'already': ['all ready'],
    'altar': ['alter'],
    'alter': ['altar'],
    'altogether': ['all together'],
    'always': ['all ways'],
    'amend': ['emend'],
    'analyst': ['annalist'],
    'annalist': ['analyst'],
    'ant': ['aunt'],
    'arc': ['ark'],
    'ariel': ['aerial'],
    'ark': ['arc'],
    'arrant': ['errant'],
    'ascent': ['assent'],
    'assent': ['ascent'],
    'assistance': ['assistants'],
    'assistants': ['assistance'],
    'ate': ['eight'],
    'atom': ['Adam'],
    'auger': ['augur'],
    'augur': ['auger'],
    'aunt': ['ant'],
    'aural': ['oral'],
    'away': ['aweigh'],
    'aweigh': ['away'],
    'awl': ['all'],
    'ax': ['acts'],
    'axel': ['axle'],
    'axes': ['axis'],
    'axis': ['axes'],
    'axle': ['axel'],
    'aye': ['eye', 'I'],
    'ayes': ['eyes'],
    'baa': ['bah'],
    'baal': ['bail', 'bale'],
    'babble': ['Babel'],
    'babel': ['babble'],
    'bad': ['bade'],
    'bade': ['bad'],
    'bah': ['baa'],
    'bail': ['bale', 'baal'],
    'bait': ['bate'],
    'baited': ['bated'],
    'bald': ['balled', 'bawled'],
    'bale': ['baal', 'bail'],
    'ball': ['bawl'],
    'balled': ['bawled', 'bald'],
    'balm': ['bomb', 'bombe'],
    'band': ['banned'],
    'banned': ['band'],
    'bard': ['barred'],
    'bare': ['bear'],
    'baron': ['barren'],
    'barred': ['bard'],
    'barren': ['baron'],
    'basal': ['basil'],
    'base': ['bass'],
    'based': ['baste'],
    'bases': ['basis'],
    'basil': ['basal'],
    'basis': ['bases'],
    'bask': ['basque'],
    'basque': ['bask'],
    'bass': ['base'],
    'baste': ['based'],
    'bate': ['bait'],
    'bated': ['baited'],
    'bawl': ['ball'],
    'bawled': ['bald', 'balled'],
    'bazaar': ['bizarre'],
    'be': ['bee'],
    'beach': ['beech'],
    'bear': ['bare'],
    'beat': ['beet'],
    'beau': ['bow'],
    'bee': ['be'],
    'beech': ['beach'],
    'been': ['bin'],
    'beer': ['bier'],
    'beet': ['beat'],
    'bell': ['belle'],
    'belle': ['bell'],
    'berry': ['bury'],
    'berth': ['birth'],
    'better': ['bettor'],
    'bettor': ['better'],
    'bib': ['bibb'],
    'bibb': ['bib'],
    'bier': ['beer'],
    'bight': ['bite', 'byte'],
    'billed': ['build'],
    'bin': ['been'],
    'bird': ['burred'],
    'birth': ['berth'],
    'bite': ['byte', 'bight'],
    'bizarre': ['bazaar'],
    'blew': ['blue'],
    'bloc': ['block'],
    'block': ['bloc'],
    'blue': ['blew'],
    'boar': ['bore'],
    'board': ['bored'],
    'boarder': ['border'],
    'bode': ['bowed'],
    'bold': ['bowled'],
    'bolder': ['boulder'],
    'bomb': ['bombe', 'balm'],
    'bombe': ['balm', 'bomb'],
    'bootie': ['booty'],
    'booty': ['bootie'],
    'border': ['boarder'],
    'bore': ['boar'],
    'bored': ['board'],
    'born': ['borne'],
    'borne': ['born'],
    'borough': ['burro', 'burrow'],
    'bough': ['bow'],
    'bouillon': ['bullion'],
    'boulder': ['bolder'],
    'bow': ['beau', 'bough'],
    'bowed': ['bode'],
    'bowled': ['bold'],
    'boy': ['buoy'],
    'braid': ['brayed'],
    'braise': ['brays'],
    'brake': ['break'],
    'brayed': ['braid'],
    'brays': ['braise'],
    'breach': ['breech'],
    'bread': ['bred'],
    'break': ['brake'],
    'bred': ['bread'],
    'breech': ['breach'],
    'brewed': ['brood'],
    'brews': ['bruise'],
    'bridal': ['bridle'],
    'bridle': ['bridal'],
    'broach': ['brooch'],
    'brooch': ['broach'],
    'brood': ['brewed'],
    'brows': ['browse'],
    'browse': ['brows'],
    'bruise': ['brews'],
    'brut': ['brute'],
    'brute': ['brut'],
    'build': ['billed'],
    'bullion': ['bouillon'],
    'buoy': ['boy'],
    'burger': ['burgher'],
    'burgher': ['burger'],
    'burred': ['bird'],
    'burro': ['burrow', 'borough'],
    'burrow': ['borough', 'burro'],
    'bury': ['berry'],
    'bussed': ['bust'],
    'bust': ['bussed'],
    'but': ['butt'],
    'butt': ['but'],
    'buy': ['by', 'bye'],
    'by': ['bye', 'buy'],
    'bye': ['buy', 'by'],
    'byte': ['bight', 'bite'],
    'cache': ['cash'],
    'caddie': ['caddy'],
    'caddy': ['caddie'],
    'cain': ['cane'],
    'calendar': ['calender'],
    'calender': ['calendar'],
    'callous': ['callus'],
    'callus': ['callous'],
    'cane': ['Cain'],
    'cannon': ['canon'],
    'canon': ['cannon'],
    'canter': ['cantor'],
    'cantor': ['canter'],
    'canvas': ['canvass'],
    'canvass': ['canvas'],
    'capital': ['capitol'],
    'capitol': ['capital'],
    'carat': ['carrot', 'caret', 'karat'],
    'caret': ['karat', 'carat', 'carrot'],
    'carol': ['carrel'],
    'carrel': ['carol'],
    'carrot': ['caret', 'karat', 'carat'],
    'cash': ['cache'],
    'cast': ['caste'],
    'caste': ['cast'],
    'caster': ['castor'],
    'castor': ['caster'],
    'cause': ['caws'],
    'caws': ['cause'],
    'cedar': ['seeder'],
    'cede': ['seed'],
    'ceiling': ['sealing'],
    'cell': ['sell'],
    'cellar': ['seller'],
    'censor': ['sensor'],
    'cent': ['scent', 'sent'],
    'cents': ['scents', 'sense'],
    'cereal': ['serial'],
    'ceres': ['series'],
    'cession': ['session'],
    'chance': ['chants'],
    'chants': ['chance'],
    'chased': ['chaste'],
    'chaste': ['chased'],
    'cheap': ['cheep'],
    'check': ['Czech'],
    'cheep': ['cheap'],
    'chews': ['choose'],
    'chic': ['sheik'],
    'chile': ['chilly', 'chili'],
    'chili': ['chile', 'chilly'],
    'chilly': ['chili', 'chile'],
    'choir': ['quire'],
    'choose': ['chews'],
    'choral': ['coral'],
    'chord': ['cord', 'cored'],
    'chute': ['shoot'],
    'cite': ['sight', 'site'],
    'cited': ['sided', 'sighted'],
    'clack': ['claque'],
    'clamber': ['clammer', 'clamor'],
    'clammer': ['clamor', 'clamber'],
    'clamor': ['clamber', 'clammer'],
    'claque': ['clack'],
    'clause': ['claws'],
    'claws': ['clause'],
    'clew': ['clue'],
    'click': ['clique'],
    'climb': ['clime'],
    'clime': ['climb'],
    'clique': ['click'],
    'close': ['clothes', 'cloze'],
    'clothes': ['cloze', 'close'],
    'cloze': ['close', 'clothes'],
    'clue': ['clew'],
    'coal': ['cole'],
    'coarse': ['course'],
    'coarser': ['courser'],
    'coat': ['cote'],
    'coax': ['cokes'],
    'coffers': ['coughers'],
    'cokes': ['coax'],
    'cole': ['coal'],
    'collard': ['collared'],
    'collared': ['collard'],
    'colonel': ['kernel'],
    'complacent': ['complaisant'],
    'complaisant': ['complacent'],
    'complement': ['compliment'],
    'complementary': ['complimentary'],
    'compliment': ['complement'],
    'complimentary': ['complementary'],
    'conceded': ['conceited'],
    'conceited': ['conceded'],
    'confirmation': ['conformation'],
    'conformation': ['confirmation'],
    'consonance': ['consonants'],
    'consonants': ['consonance'],
    'continence': ['continents'],
    'continents': ['continence'],
    'coo': ['coup'],
    'coop': ['coupe'],
    'cops': ['copse'],
    'copse': ['cops'],
    'coral': ['choral'],
    'cord': ['cored', 'chord'],
    'core': ['corps'],
    'cored': ['chord', 'cord'],
    'corps': ['core'],
    'correspondence': ['correspondents'],
    'correspondents': ['correspondence'],
    'cote': ['coat'],
    'coughers': ['coffers'],
    'council': ['counsel'],
    'counsel': ['council'],
    'coup': ['coo'],
    'coupe': ['coop'],
    'course': ['coarse'],
    'courser': ['coarser'],
    'cousin': ['cozen'],
    'coward': ['cowered'],
    'cowered': ['coward'],
    'coy': ['koi'],
    'cozen': ['cousin'],
    'craft': ['kraft'],
    'crape': ['crepe'],
    'crawl': ['kraal'],
    'creak': ['creek'],
    'creek': ['creak'],
    'crepe': ['crape'],
    'crewel': ['cruel'],
    'crews': ['cruise'],
    'cruel': ['crewel'],
    'cruise': ['crews'],
    'cue': ['queue'],
    'currant': ['current'],
    'current': ['currant'],
    'curser': ['cursor'],
    'cursor': ['curser'],
    'cygnet': ['signet'],
    'cymbal': ['symbol'],
    'cypress': ['Cyprus'],
    'cyprus': ['cypress'],
    'czech': ['check'],
    'dane': ['deign'],
    'days': ['daze'],
    'daze': ['days'],
    'dear': ['deer'],
    'deer': ['dear'],
    'defused': ['diffused'],
    'deign': ['Dane'],
    'dense': ['dents'],
    'dents': ['dense'],
    'descent': ['dissent'],
    'desert': ['dessert'],
    'dessert': ['desert'],
    'dew': ['do', 'due'],
    'die': ['dye'],
    'diffused': ['defused'],
    'disburse': ['disperse'],
    'discreet': ['discrete'],
    'discrete': ['discreet'],
    'disperse': ['disburse'],
    'dissent': ['descent'],
    'do': ['due', 'dew'],
    'doc': ['dock'],
    'dock': ['doc'],
    'doe': ['dough'],
    'does': ['doze'],
    'done': ['dun'],
    'dough': ['do', 'doe'],
    'doze': ['does'],
    'draft': ['draught'],
    'draught': ['draft'],
    'dual': ['duel'],
    'ducked': ['duct'],
    'ducks': ['ducts'],
    'duct': ['ducked'],
    'ducts': ['ducks'],
    'due': ['dew', 'do'],
    'duel': ['dual'],
    'dun': ['done'],
    'dye': ['die'],
    'dyeing': ['dying'],
    'dying': ['dyeing'],
    'earn': ['urn'],
    'eave': ['eve'],
    'edition': ['addition'],
    'eek': ['eke'],
    'effect': ['affect'],
    'effected': ['affected'],
    'effects': ['affects'],
    'eight': ['ate'],
    'eke': ['eek'],
    'elicit': ['illicit'],
    'elude': ['allude'],
    'eluded': ['alluded'],
    'elusive': ['illusive', 'allusive'],
    'emend': ['amend'],
    'enumerable': ['innumerable'],
    'err': ['air', 'heir'],
    'errant': ['arrant'],
    'eve': ['eave'],
    'ewe': ['you', 'yew'],
    'ewes': ['yews', 'use'],
    'exceed': ['accede'],
    'except': ['accept'],
    'exercise': ['exorcise'],
    'exorcise': ['exercise'],
    'eye': ['I', 'aye'],
    'eyed': ['I\'d'],
    'eyelet': ['islet'],
    'eyes': ['ayes'],
    'facts': ['fax'],
    'faint': ['feint'],
    'fair': ['fare'],
    'fairy': ['ferry'],
    'fare': ['fair'],
    'fate': ['fete'],
    'faun': ['fawn'],
    'faux': ['foe'],
    'fawn': ['faun'],
    'fax': ['facts'],
    'faze': ['phase'],
    'feat': ['feet'],
    'feet': ['feat'],
    'feint': ['faint'],
    'fends': ['fens'],
    'fens': ['fends'],
    'ferry': ['fairy'],
    'fete': ['fate'],
    'few': ['phew'],
    'fill': ['Phil'],
    'find': ['fined'],
    'fined': ['find'],
    'finish': ['Finnish'],
    'finnish': ['finish'],
    'fir': ['fur'],
    'fisher': ['fissure'],
    'fissure': ['fisher'],
    'flair': ['flare'],
    'flare': ['flair'],
    'flea': ['flee'],
    'flee': ['flea'],
    'flew': ['flu', 'flue'],
    'flier': ['flyer'],
    'flocks': ['phlox'],
    'floe': ['flow'],
    'flour': ['flower'],
    'flow': ['floe'],
    'flower': ['flour'],
    'flu': ['flue', 'flew'],
    'flue': ['flew', 'flu'],
    'flyer': ['flier'],
    'foaled': ['fold'],
    'foe': ['faux'],
    'fold': ['foaled'],
    'for': ['four', 'fore'],
    'fore': ['for', 'four'],
    'foregone': ['forgone'],
    'foreword': ['forward'],
    'forgone': ['foregone'],
    'fort': ['forte'],
    'forte': ['fort'],
    'forth': ['fourth'],
    'forward': ['foreword'],
    'foul': ['fowl'],
    'four': ['fore', 'for'],
    'fourth': ['forth'],
    'fowl': ['foul'],
    'franc': ['frank'],
    'frank': ['franc'],
    'frays': ['phrase'],
    'frees': ['freeze', 'frieze'],
    'freeze': ['frieze', 'frees'],
    'friar': ['fryer'],
    'frieze': ['frees', 'freeze'],
    'fryer': ['friar'],
    'fur': ['fir'],
    'gaff': ['gaffe'],
    'gaffe': ['gaff'],
    'gail': ['gale'],
    'gait': ['gate'],
    'gale': ['Gail'],
    'gamble': ['gambol'],
    'gambol': ['gamble'],
    'gate': ['gait'],
    'gel': ['jell'],
    'gene': ['jean'],
    'gibe': ['jibe'],
    'gild': ['guild'],
    'gilder': ['guilder'],
    'gilt': ['guilt'],
    'gneiss': ['nice'],
    'gnome': ['Nome'],
    'gnu': ['knew', 'new'],
    'gofer': ['gopher'],
    'gopher': ['gofer'],
    'gored': ['gourd'],
    'gorilla': ['guerilla'],
    'gourd': ['gored'],
    'grade': ['grayed'],
    'graft': ['graphed'],
    'graham': ['gram'],
    'gram': ['graham'],
    'graphed': ['graft'],
    'grate': ['great'],
    'grater': ['greater'],
    'grayed': ['grade'],
    'grays': ['graze'],
    'graze': ['grays'],
    'grease': ['Greece'],
    'great': ['grate'],
    'greater': ['grater'],
    'greece': ['grease'],
    'grill': ['grille'],
    'grille': ['grill'],
    'grisly': ['grizzly'],
    'grizzly': ['grisly'],
    'groan': ['grown'],
    'grown': ['groan'],
    'guerilla': ['gorilla'],
    'guessed': ['guest'],
    'guest': ['guessed'],
    'guild': ['gild'],
    'guilder': ['gilder'],
    'guilt': ['gilt'],
    'gym': ['Jim'],
    'hail': ['hale'],
    'hair': ['hare'],
    'hale': ['hail'],
    'hall': ['haul'],
    'halve': ['have'],
    'handmade': ['handmaid'],
    'handmaid': ['handmade'],
    'handsome': ['hansom'],
    'hangar': ['hanger'],
    'hanger': ['hangar'],
    'hansom': ['handsome'],
    'hare': ['hair'],
    'hart': ['heart'],
    'haul': ['hall'],
    'have': ['halve'],
    'hay': ['hey'],
    'hays': ['haze'],
    'haze': ['hays'],
    'heal': ['heel', 'hell\''],
    'hear': ['here'],
    'heard': ['herd'],
    'heart': ['hart'],
    'hed\'': ['heed'],
    'heed': ['hed\''],
    'heel': ['hell\'', 'heal'],
    'heir': ['err', 'air'],
    'hell\'': ['heal', 'heel'],
    'herd': ['heard'],
    'here': ['hear'],
    'heroin': ['heroine'],
    'heroine': ['heroin'],
    'hertz': ['hurts'],
    'hew': ['hue', 'Hugh'],
    'hey': ['hay'],
    'hi': ['high'],
    'high': ['hi'],
    'higher': ['hire'],
    'him': ['hymn'],
    'hire': ['higher'],
    'ho': ['hoe'],
    'hoard': ['horde'],
    'hoarse': ['horse'],
    'hoe': ['ho'],
    'hoes': ['hose'],
    'hold': ['holed'],
    'hole': ['whole'],
    'holed': ['hold'],
    'holey': ['holy', 'wholly'],
    'holy': ['wholly', 'holey'],
    'hoop': ['whoop'],
    'horde': ['hoard'],
    'horse': ['hoarse'],
    'hose': ['hoes'],
    'hostel': ['hostile'],
    'hostile': ['hostel'],
    'hour': ['our'],
    'hue': ['Hugh', 'hew'],
    'hugh': ['hew', 'hue'],
    'humerus': ['humorous'],
    'humorous': ['humerus'],
    'hurts': ['hertz'],
    'hymn': ['him'],
    'i': ['aye', 'eye'],
    'i\'d': ['eyed'],
    'idle': ['idol', 'idyll'],
    'idol': ['idyll', 'idle'],
    'idyll': ['idle', 'idol'],
    'i\'ll': ['aisle', 'isle'],
    'illicit': ['elicit'],
    'illusion': ['allusion'],
    'illusive': ['allusive', 'elusive'],
    'immanent': ['imminent'],
    'imminent': ['immanent'],
    'impassable': ['impassible'],
    'impassible': ['impassable'],
    'in': ['inn'],
    'incite': ['insight'],
    'inn': ['in'],
    'innocence': ['innocents'],
    'innocents': ['innocence'],
    'innumerable': ['enumerable'],
    'insight': ['incite'],
    'instance': ['instants'],
    'instants': ['instance'],
    'intense': ['intents'],
    'intents': ['intense'],
    'isle': ['I\'ll', 'aisle'],
    'islet': ['eyelet'],
    'its': ['it\'s'],
    'it\'s': ['its'],
    'jam': ['jamb'],
    'jamb': ['jam'],
    'jean': ['gene'],
    'jell': ['gel'],
    'jibe': ['gibe'],
    'jim': ['gym'],
    'jinks': ['jinx'],
    'jinx': ['jinks'],
    'karat': ['carat', 'carrot', 'caret'],
    'kernel': ['colonel'],
    'knap': ['nap'],
    'knave': ['nave'],
    'knead': ['kneed', 'need'],
    'kneed': ['need', 'knead'],
    'knew': ['new', 'gnu'],
    'knickers': ['nickers'],
    'knight': ['night'],
    'knit': ['nit'],
    'knock': ['nock'],
    'knot': ['not'],
    'know': ['no'],
    'knows': ['nose'],
    'koi': ['coy'],
    'kraal': ['crawl'],
    'kraft': ['craft'],
    'lacks': ['lax'],
    'ladder': ['latter'],
    'lade': ['laid'],
    'laid': ['lade'],
    'lain': ['lane'],
    'lama': ['llama'],
    'lane': ['lain'],
    'lapps': ['laps', 'lapse'],
    'laps': ['lapse', 'lapps'],
    'lapse': ['lapps', 'laps'],
    'latter': ['ladder'],
    'lax': ['lacks'],
    'lay': ['lei'],
    'lays': ['laze', 'leis'],
    'laze': ['leis', 'lays'],
    'lea': ['lee'],
    'leach': ['leech'],
    'lead': ['led'],
    'leak': ['leek'],
    'lean': ['lien'],
    'leased': ['least'],
    'least': ['leased'],
    'led': ['lead'],
    'lee': ['lea'],
    'leech': ['leach'],
    'leek': ['leak'],
    'lei': ['lay'],
    'leis': ['lays', 'laze'],
    'lends': ['lens'],
    'lens': ['lends'],
    'lessen': ['lesson'],
    'lesson': ['lessen'],
    'lets': ['let\'s'],
    'let\'s': ['lets'],
    'levee': ['levy'],
    'levy': ['levee'],
    'liar': ['lier', 'lyre'],
    'lichen': ['liken'],
    'lie': ['lye'],
    'lien': ['lean'],
    'lier': ['lyre', 'liar'],
    'lieu': ['Lou'],
    'liken': ['lichen'],
    'links': ['lynx'],
    'literal': ['littoral'],
    'littoral': ['literal'],
    'llama': ['lama'],
    'lo': ['low'],
    'load': ['lode', 'lowed'],
    'loan': ['lone'],
    'loath': ['loathe'],
    'loathe': ['loath'],
    'loch': ['lock'],
    'lochs': ['locks', 'lox'],
    'lock': ['loch'],
    'locks': ['lox', 'lochs'],
    'lode': ['lowed', 'load'],
    'lone': ['loan'],
    'loot': ['lute'],
    'lou': ['lieu'],
    'low': ['lo'],
    'lowed': ['load', 'lode'],
    'lox': ['lochs', 'locks'],
    'lumbar': ['lumber'],
    'lumber': ['lumbar'],
    'lute': ['loot'],
    'lye': ['lie'],
    'lynx': ['links'],
    'lyre': ['liar', 'lier'],
    'madder': ['matter'],
    'made': ['maid'],
    'maid': ['made'],
    'mail': ['male'],
    'main': ['mane', 'Maine'],
    'maine': ['main', 'mane'],
    'maize': ['maze'],
    'male': ['mail'],
    'mall': ['maul'],
    'mane': ['Maine', 'main'],
    'manner': ['manor'],
    'manor': ['manner'],
    'mantel': ['mantle'],
    'mantle': ['mantel'],
    'marc': ['mark'],
    'mare': ['mayor'],
    'mark': ['marc'],
    'marry': ['merry', 'Mary'],
    'marshal': ['martial'],
    'marten': ['martin'],
    'martial': ['marshal'],
    'martin': ['marten'],
    'mary': ['marry', 'merry'],
    'massed': ['mast'],
    'mast': ['massed'],
    'mat': ['matte'],
    'matte': ['mat'],
    'matter': ['madder'],
    'maul': ['mall'],
    'may be': ['maybe'],
    'maybe': ['may be'],
    'mayor': ['mare'],
    'maze': ['maize'],
    'mean': ['mien'],
    'meat': ['meet', 'mete'],
    'meatier': ['meteor'],
    'medal': ['metal', 'mettle', 'meddle'],
    'meddle': ['medal', 'metal', 'mettle'],
    'meet': ['mete', 'meat'],
    'merry': ['Mary', 'marry'],
    'metal': ['mettle', 'meddle', 'medal'],
    'mete': ['meat', 'meet'],
    'meteor': ['meatier'],
    'mettle': ['meddle', 'medal', 'metal'],
    'mewl': ['mule'],
    'mews': ['muse'],
    'mien': ['mean'],
    'might': ['mite'],
    'mil': ['mill'],
    'mill': ['mil'],
    'mince': ['mints'],
    'mind': ['mined'],
    'mined': ['mind'],
    'miner': ['minor'],
    'minor': ['miner'],
    'mints': ['mince'],
    'missal': ['missile'],
    'missed': ['mist'],
    'misses': ['Mrs.'],
    'missile': ['missal'],
    'mist': ['missed'],
    'mite': ['might'],
    'moan': ['mown'],
    'moat': ['mote'],
    'mode': ['mowed'],
    'mood': ['mooed'],
    'mooed': ['mood'],
    'moose': ['mousse'],
    'morn': ['mourn'],
    'morning': ['mourning'],
    'mote': ['moat'],
    'mourn': ['morn'],
    'mourning': ['morning'],
    'mousse': ['moose'],
    'mowed': ['mode'],
    'mown': ['moan'],
    'mrs.': ['misses'],
    'mucous': ['mucus'],
    'mucus': ['mucous'],
    'mule': ['mewl'],
    'muscle': ['mussel'],
    'muse': ['mews'],
    'mussed': ['must'],
    'mussel': ['muscle'],
    'must': ['mussed'],
    'mustard': ['mustered'],
    'mustered': ['mustard'],
    'nap': ['knap'],
    'naval': ['navel'],
    'nave': ['knave'],
    'navel': ['naval'],
    'nay': ['neigh'],
    'need': ['knead', 'kneed'],
    'neigh': ['nay'],
    'new': ['gnu', 'knew'],
    'nice': ['gneiss', 'niece'],
    'nickers': ['knickers'],
    'niece': ['Nice'],
    'night': ['knight'],
    'nit': ['knit'],
    'no': ['know'],
    'nock': ['knock'],
    'nome': ['gnome'],
    'none': ['nun'],
    'nose': ['knows'],
    'not': ['knot'],
    'nun': ['none'],
    'oar': ['or', 'ore'],
    'ode': ['owed'],
    'oh': ['owe'],
    'one': ['won'],
    'or': ['ore', 'oar'],
    'oral': ['aural'],
    'ore': ['oar', 'or'],
    'our': ['hour'],
    'outcast': ['outcaste'],
    'outcaste': ['outcast'],
    'overdo': ['overdue'],
    'overdue': ['overdo'],
    'overseas': ['oversees'],
    'oversees': ['overseas'],
    'owe': ['oh'],
    'owed': ['ode'],
    'paced': ['paste'],
    'packed': ['pact'],
    'pact': ['packed'],
    'padded': ['patted'],
    'pail': ['pale'],
    'pain': ['pane'],
    'pair': ['pare', 'pear'],
    'palate': ['palette', 'pallet'],
    'pale': ['pail'],
    'palette': ['pallet', 'palate'],
    'pall': ['Paul'],
    'pallet': ['palate', 'palette'],
    'pane': ['pain'],
    'pare': ['pear', 'pair'],
    'parish': ['perish'],
    'parlay': ['parley'],
    'parley': ['parlay'],
    'passed': ['past'],
    'past': ['passed'],
    'paste': ['paced'],
    'patience': ['patients'],
    'patients': ['patience'],
    'patted': ['padded'],
    'paul': ['pall'],
    'pause': ['paws'],
    'paws': ['pause'],
    'pea': ['pee'],
    'peace': ['piece'],
    'peak': ['peek', 'pique'],
    'peal': ['peel'],
    'pear': ['pair', 'pare'],
    'pearl': ['purl'],
    'peas': ['pees'],
    'peat': ['Pete'],
    'pedal': ['peddle', 'petal'],
    'peddle': ['petal', 'pedal'],
    'pee': ['pea'],
    'peek': ['pique', 'peak'],
    'peel': ['peal'],
    'peer': ['pier'],
    'pees': ['peas'],
    'penance': ['pennants'],
    'pennants': ['penance'],
    'per': ['purr'],
    'perish': ['parish'],
    'pervade': ['purveyed'],
    'petal': ['pedal', 'peddle'],
    'pete': ['peat'],
    'petrel': ['petrol'],
    'petrol': ['petrel'],
    'phase': ['faze'],
    'phew': ['few'],
    'phil': ['fill'],
    'phlox': ['flocks'],
    'phrase': ['frays'],
    'pi': ['pie'],
    'pidgin': ['pigeon'],
    'pie': ['pi'],
    'piece': ['peace'],
    'pier': ['peer'],
    'pigeon': ['pidgin'],
    'pilate': ['pilot'],
    'pilot': ['pilate'],
    'pique': ['peak', 'peek'],
    'pistil': ['pistol'],
    'pistol': ['pistil'],
    'plain': ['plane'],
    'plait': ['plate'],
    'plane': ['plain'],
    'plate': ['plait'],
    'pleas': ['please'],
    'please': ['pleas'],
    'plum': ['plumb'],
    'plumb': ['plum'],
    'pole': ['poll'],
    'poll': ['pole'],
    'pore': ['pour'],
    'pour': ['pore'],
    'praise': ['prays', 'preys'],
    'pray': ['prey'],
    'prays': ['preys', 'praise'],
    'precedence': ['precedents'],
    'precedents': ['precedence'],
    'premier': ['premiere'],
    'premiere': ['premier'],
    'presence': ['presents'],
    'presents': ['presence'],
    'prey': ['pray'],
    'preys': ['praise', 'prays'],
    'pride': ['pried'],
    'pried': ['pride'],
    'primer': ['primmer'],
    'primmer': ['primer'],
    'prince': ['prints'],
    'principal': ['principle'],
    'principle': ['principal'],
    'prints': ['prince'],
    'profit': ['prophet'],
    'prophet': ['profit'],
    'pros': ['prose'],
    'prose': ['pros'],
    'purl': ['pearl'],
    'purr': ['per'],
    'purveyed': ['pervade'],
    'quarts': ['quartz'],
    'quartz': ['quarts'],
    'queue': ['cue'],
    'quince': ['quints'],
    'quints': ['quince'],
    'quire': ['choir'],
    'rack': ['wrack'],
    'rain': ['reign', 'rein'],
    'raise': ['rays', 'raze'],
    'rap': ['wrap'],
    'rapped': ['rapt', 'wrapped'],
    'rapper': ['wrapper'],
    'rapt': ['wrapped', 'rapped'],
    'rays': ['raze', 'raise'],
    'raze': ['raise', 'rays'],
    'read': ['red', 'reed'],
    'real': ['reel'],
    'red': ['read'],
    'reed': ['read'],
    'reek': ['wreak'],
    'reel': ['real'],
    'reign': ['rein', 'rain'],
    'rein': ['rain', 'reign'],
    'residence': ['residents'],
    'residents': ['residence'],
    'rest': ['wrest'],
    'retch': ['wretch'],
    'review': ['revue'],
    'revue': ['review'],
    'rheum': ['room'],
    'rigger': ['rigor'],
    'right': ['rite', 'write'],
    'rigor': ['rigger'],
    'ring': ['wring'],
    'rite': ['write', 'right'],
    'road': ['rode', 'rowed'],
    'roam': ['Rome'],
    'rode': ['rowed', 'road'],
    'roe': ['row'],
    'role': ['roll'],
    'roll': ['role'],
    'rome': ['roam'],
    'room': ['rheum'],
    'roomer': ['rumor'],
    'root': ['route'],
    'rose': ['rows'],
    'rote': ['wrote'],
    'rough': ['ruff'],
    'rouse': ['rows'],
    'route': ['root'],
    'row': ['roe'],
    'rowed': ['road', 'rode'],
    'rows': ['rose'],
    'rude': ['rued'],
    'rued': ['rude'],
    'ruff': ['rough'],
    'rumor': ['roomer'],
    'rung': ['wrung'],
    'russell': ['rustle'],
    'rustle': ['russell'],
    'rye': ['wry'],
    'sac': ['sack'],
    'sachet': ['sashay'],
    'sack': ['sac'],
    'sacks': ['sax'],
    'sail': ['sale'],
    'sale': ['sail'],
    'sane': ['seine'],
    'sari': ['sorry'],
    'sashay': ['sachet'],
    'saver': ['savor'],
    'savor': ['saver'],
    'sax': ['sacks'],
    'scene': ['seen'],
    'scent': ['sent', 'cent'],
    'scents': ['sense', 'cents'],
    'scull': ['skull'],
    'sea': ['see'],
    'sealing': ['ceiling'],
    'seam': ['seem'],
    'sear': ['seer', 'sere'],
    'seas': ['sees', 'seize'],
    'see': ['sea'],
    'seed': ['cede'],
    'seeder': ['cedar'],
    'seem': ['seam'],
    'seen': ['scene'],
    'seer': ['sere', 'sear'],
    'sees': ['seize', 'seas'],
    'seine': ['sane'],
    'seize': ['seas', 'sees'],
    'sell': ['cell'],
    'seller': ['cellar'],
    'sense': ['cents', 'scents'],
    'sensor': ['censor'],
    'sent': ['cent', 'scent'],
    'sere': ['sear', 'seer'],
    'serf': ['surf'],
    'serge': ['surge'],
    'serial': ['cereal'],
    'series': ['Ceres'],
    'session': ['cession'],
    'sew': ['so', 'sow'],
    'shear': ['sheer'],
    'sheer': ['shear'],
    'sheik': ['chic'],
    'shoe': ['shoo'],
    'shone': ['shown'],
    'shoo': ['shoe'],
    'shoot': ['chute'],
    'shown': ['shone'],
    'sic': ['sick'],
    'sick': ['sic'],
    'side': ['sighed'],
    'sided': ['sighted', 'cited'],
    'sighed': ['side'],
    'sighs': ['size'],
    'sight': ['site', 'cite'],
    'sighted': ['cited', 'sided'],
    'signet': ['cygnet'],
    'sink': ['sync'],
    'sioux': ['sue'],
    'site': ['cite', 'sight'],
    'size': ['sighs'],
    'skull': ['scull'],
    'slay': ['sleigh'],
    'sleigh': ['slay'],
    'sleight': ['slight'],
    'slew': ['slue', 'slough'],
    'slight': ['sleight'],
    'sloe': ['slow'],
    'slough': ['slew', 'slue'],
    'slow': ['sloe'],
    'slue': ['slough', 'slew'],
    'so': ['sow', 'sew'],
    'soar': ['sore'],
    'soared': ['sword'],
    'sold': ['soled'],
    'sole': ['soul'],
    'soled': ['sold'],
    'some': ['sum'],
    'son': ['sun'],
    'soot': ['suit'],
    'sore': ['soar'],
    'sorry': ['sari'],
    'soul': ['sole'],
    'sow': ['sew', 'so'],
    'spade': ['spayed'],
    'spayed': ['spade'],
    'staid': ['stayed'],
    'stair': ['stare'],
    'stake': ['steak'],
    'stare': ['stair'],
    'stationary': ['stationery'],
    'stationery': ['stationary'],
    'stayed': ['staid'],
    'steak': ['stake'],
    'steal': ['steel'],
    'steel': ['steal'],
    'step': ['steppe'],
    'steppe': ['step'],
    'stile': ['style'],
    'straight': ['strait'],
    'straightened': ['straitened'],
    'strait': ['straight'],
    'straitened': ['straightened'],
    'style': ['stile'],
    'sue': ['Sioux'],
    'suede': ['swayed'],
    'suit': ['soot'],
    'suite': ['sweet'],
    'sum': ['some'],
    'summary': ['summery'],
    'summery': ['summary'],
    'sun': ['son'],
    'sundae': ['Sunday'],
    'sunday': ['sundae'],
    'surf': ['serf'],
    'surge': ['serge'],
    'swayed': ['suede'],
    'sweet': ['suite'],
    'sword': ['soared'],
    'symbol': ['cymbal'],
    'sync': ['sink'],
    'tacked': ['tact'],
    'tacks': ['tax'],
    'tact': ['tacked'],
    'tail': ['tale'],
    'tale': ['tail'],
    'taper': ['tapir'],
    'tapir': ['taper'],
    'tarry': ['terry'],
    'taught': ['taut'],
    'taupe': ['tope'],
    'taut': ['taught'],
    'tax': ['tacks'],
    'tea': ['tee'],
    'team': ['teem'],
    'tear': ['tier'],
    'teas': ['tease', 'tees'],
    'tease': ['tees', 'teas'],
    'tee': ['tea'],
    'teem': ['team'],
    'tees': ['teas', 'tease'],
    'tends': ['tens'],
    'tens': ['tends'],
    'tense': ['tents'],
    'tents': ['tense'],
    'tern': ['turn'],
    'terry': ['tarry'],
    'thai': ['tie'],
    'the': ['thee'],
    'thee': ['the'],
    'their': ['there', 'they\'re'],
    'theirs': ['there\'s'],
    'there': ['they\'re', 'their'],
    'there\'s': ['theirs'],
    'they\'re': ['their', 'there'],
    'threw': ['through'],
    'throes': ['throws'],
    'throne': ['thrown'],
    'through': ['threw'],
    'thrown': ['throne'],
    'throws': ['throes'],
    'thyme': ['time'],
    'tic': ['tick'],
    'tick': ['tic'],
    'tide': ['tied'],
    'tie': ['Thai'],
    'tied': ['tide'],
    'tier': ['tear'],
    'tigress': ['Tigris'],
    'tigris': ['tigress'],
    'timber': ['timbre'],
    'timbre': ['timber'],
    'time': ['thyme'],
    'to': ['too', 'two'],
    'toad': ['toed', 'towed'],
    'toe': ['tow'],
    'toed': ['towed', 'toad'],
    'told': ['tolled'],
    'tolled': ['told'],
    'too': ['two', 'to'],
    'tool': ['tulle'],
    'tooter': ['Tudor', 'tutor'],
    'tope': ['taupe'],
    'tort': ['torte'],
    'torte': ['tort'],
    'tortuous': ['torturous'],
    'torturous': ['tortuous'],
    'tow': ['toe'],
    'towed': ['toad', 'toed'],
    'tracked': ['tract'],
    'tract': ['tracked'],
    'trader': ['traitor'],
    'traitor': ['trader'],
    'troop': ['troupe'],
    'troupe': ['troop'],
    'trussed': ['trust'],
    'trust': ['trussed'],
    'tucks': ['tux'],
    'tudor': ['tutor', 'tooter'],
    'tulle': ['tool'],
    'turban': ['turbine'],
    'turbine': ['turban'],
    'turn': ['tern'],
    'tutor': ['tooter', 'Tudor'],
    'tux': ['tucks'],
    'two': ['to', 'too'],
    'udder': ['utter'],
    'undo': ['undue'],
    'undue': ['undo'],
    'urn': ['earn'],
    'use': ['ewes', 'yews'],
    'utter': ['udder'],
    'vain': ['vane', 'vein'],
    'valance': ['valence'],
    'vale': ['veil'],
    'valence': ['valance'],
    'vane': ['vein', 'vain'],
    'vary': ['very'],
    'veil': ['vale'],
    'vein': ['vain', 'vane'],
    'venous': ['Venus'],
    'venus': ['venous'],
    'verses': ['versus'],
    'versus': ['verses'],
    'very': ['vary'],
    'vial': ['vile'],
    'vice': ['vise'],
    'vile': ['vial'],
    'vise': ['vice'],
    'wade': ['weighed'],
    'wader': ['waiter'],
    'wail': ['whale', 'wale'],
    'wails': ['Wales', 'whales'],
    'wain': ['wane', 'Wayne'],
    'waist': ['waste'],
    'wait': ['weight'],
    'waiter': ['wader'],
    'waive': ['wave'],
    'wale': ['wail', 'whale'],
    'wales': ['whales', 'wails'],
    'walk': ['wok'],
    'wane': ['Wayne', 'wain'],
    'want': ['wont'],
    'war': ['wore'],
    'ware': ['wear', 'where'],
    'wares': ['where\'s', 'wears'],
    'warn': ['worn'],
    'waste': ['waist'],
    'watt': ['what'],
    'wave': ['waive'],
    'wax': ['whacks'],
    'way': ['weigh', 'whey'],
    'wayne': ['wain', 'wane'],
    'ways': ['weighs'],
    'we': ['wee'],
    'weak': ['week'],
    'wear': ['where', 'ware'],
    'wears': ['wares', 'where\'s'],
    'weather': ['whether', 'wether'],
    'weave': ['we\'ve'],
    'we\'d': ['weed'],
    'wee': ['we'],
    'weed': ['we\'d'],
    'week': ['weak'],
    'weigh': ['whey', 'way'],
    'weighed': ['wade'],
    'weighs': ['ways'],
    'weight': ['wait'],
    'we\'ll': ['wheel'],
    'were': ['whir'],
    'wet': ['whet'],
    'wether': ['weather', 'whether'],
    'we\'ve': ['weave'],
    'whacks': ['wax'],
    'whale': ['wale', 'wail'],
    'whales': ['wails', 'Wales'],
    'what': ['watt'],
    'wheel': ['we\'ll'],
    'where': ['ware', 'wear'],
    'where\'s': ['wears', 'wares'],
    'whet': ['wet'],
    'whether': ['wether', 'weather'],
    'whey': ['way', 'weigh'],
    'which': ['witch'],
    'while': ['wile'],
    'whine': ['wine'],
    'whined': ['wind', 'wined'],
    'whir': ['were'],
    'whirled': ['whorled', 'world'],
    'whirred': ['word'],
    'whoa': ['woe'],
    'whole': ['hole'],
    'wholly': ['holey', 'holy'],
    'whoop': ['hoop'],
    'whorled': ['world', 'whirled'],
    'who\'s': ['whose'],
    'whose': ['who\'s'],
    'wile': ['while'],
    'wind': ['wined', 'whined'],
    'wine': ['whine'],
    'wined': ['whined', 'wind'],
    'witch': ['which'],
    'woe': ['whoa'],
    'wok': ['walk'],
    'won': ['one'],
    'wont': ['want'],
    'wood': ['would'],
    'word': ['whirred'],
    'wore': ['war'],
    'world': ['whirled', 'whorled'],
    'worn': ['warn'],
    'would': ['wood'],
    'wrack': ['rack'],
    'wrap': ['rap'],
    'wrapped': ['rapped', 'rapt'],
    'wrapper': ['rapper'],
    'wreak': ['reek'],
    'wrest': ['rest'],
    'wretch': ['retch'],
    'wring': ['ring'],
    'write': ['right', 'rite'],
    'wrote': ['rote'],
    'wrung': ['rung'],
    'wry': ['rye'],
    'yew': ['ewe', 'you'],
    'yews': ['use', 'ewes'],
    'yoke': ['yolk'],
    'yolk': ['yoke'],
    'yore': ['your', 'you\'re'],
    'you': ['yew', 'ewe'],
    'you\'ll': ['Yule'],
    'your': ['you\'re', 'yore'],
    'you\'re': ['yore', 'your'],
    'yule': ['you\'ll']
};